stages:
  - build
  - test
  - report

# build_app:
#   image: maven:3.8-openjdk-17
#   tags:
#     - pppp
#   stage: build
#   script:
#     - mvn package
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"

run_tests:
  image: maven:3.8-openjdk-17
  tags:
    - pppp
  stage: test
  script:
    - export DISPLAY=:99
    - mvn verify
    - awk -F"," '{ total += $4 + $5; covered += $5 } END { print 100*covered/total, "% covered" }' target/site/jacoco/jacoco.csv
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/site/jacoco/jacoco.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"

run_coverage:
  stage: test
  tags:
    - pppp
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["run_tests"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"

sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp
  script:
    - sigridci.py --customer utst --system P42023T03 --source .
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    reports:
      junit: "sigrid-ci-output/sigridci-junit-format-report.xml"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp
  script:
    - sigridci.py --customer utst --system P42023T03 --source . --publish
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push") && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
